### PR TITLE
[WIP] Get Runes working agian

### PR DESCRIPTION
**Pull request by 0xilly**
Got rid of a lot of compile errors still have some to go

### CODE REVIEW

**Comment by 0xilly** [comment]
Woo! just 11 more classes to fix till I can get this thing to run
screenshot 37

**Comment by 0xilly** [comment]
side note this PR needs #82 in order to work

**Comment by 0xilly** [comment]
Ok looks like there is an issue with persistent rune that is based on the calling the client from the server... Yay...

```
--- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/16/17 2:55 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/server/dedicated/DedicatedServer
	at net.minecraftforge.fml.server.FMLServerHandler.allowLogins(FMLServerHandler.java:321)
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:301)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:551)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.dedicated.DedicatedServer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@6f463d4f from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 6 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/server/dedicated/DedicatedServer for invalid side CLIENT
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 8 more
```

**Comment by 0xilly** [comment]
Woo new crash
Looks like its called from  EntityPlayerMP
```
--- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 9/16/17 3:14 PM
Description: Saving entity NBT

java.lang.NullPointerException: Saving entity NBT
	at net.minecraftforge.fml.server.FMLServerHandler.getDataFixer(FMLServerHandler.java:356)
	at net.minecraftforge.fml.common.FMLCommonHandler.getDataFixer(FMLCommonHandler.java:766)
	at net.minecraft.entity.player.EntityPlayer.writeEntityToNBT(EntityPlayer.java:1021)
	at net.minecraft.entity.player.EntityPlayerMP.writeEntityToNBT(EntityPlayerMP.java:275)
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1955)
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:30)
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:986)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.server.FMLServerHandler.getDataFixer(FMLServerHandler.java:356)
	at net.minecraftforge.fml.common.FMLCommonHandler.getDataFixer(FMLCommonHandler.java:766)
	at net.minecraft.entity.player.EntityPlayer.writeEntityToNBT(EntityPlayer.java:1021)
	at net.minecraft.entity.player.EntityPlayerMP.writeEntityToNBT(EntityPlayerMP.java:275)

-- Entity being saved --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 428
	Entity Name: Player953
	Entity's Exact location: 77.58, 68.00, 253.29
	Entity's Block location: World: (77,68,253), Chunk: (at 13,4,13 in 4,15; contains blocks 64,0,240 to 79,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.Entity.writeToNBT(Entity.java:1955)
	at net.minecraft.server.integrated.IntegratedPlayerList.writePlayerData(IntegratedPlayerList.java:30)
	at net.minecraft.server.management.PlayerList.saveAllPlayerData(PlayerList.java:986)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:176)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by josiahseaman** [comment]
You're on a roll aren't you?  Could you please pull and merge 1.12 branch?  That way, there's no Merge Conflict to resolve in the Pull Request.

**Comment by 0xilly** [comment]
im going to have to force merge into mine. It diverged somewhere...

**Comment by 0xilly** [comment]
That was painful

**Comment by 0xilly** [comment]
Ok so there is a problem when saving the world... Way

**Comment by 0xilly** [comment]
Found the line in question https://github.com/Runix-Minecraft/Runix/blob/reTeir/src/main/java/com/newlinegaming/Runix/PersistentRune.java#L292

**Comment by 0xilly** [comment]
ok imma take a little break ill try to get the rest working later tonight

**Comment by 0xilly** [comment]
@josiahseaman can you take a look at the patterns I'm going to take a nap

**Comment by josiahseaman** [comment]
I'm currently working on merging reTier into 1.12.  In the future, please check on the status of other branches before you make a bunch of changes.  I think in general, we should have 1 stable (master), 1 staging (1.12) and one branch for each of us (Bloodstone, Illy, Josiah).  Your branch should at least be up to date with 1.12 as the staging branch.  On the plus side, we agree on most of these changes, since they're identical in the merge.

Network looks like a bit of a mess right now:
https://github.com/Runix-Minecraft/Runix/network

**Comment by josiahseaman** [comment]
Ok, the merge went well!  It was about 50/50 whether I accepted your solution or my solution on a conflict.  So that's a good sign that we're getting useful options out of it.  

@blood-stone  I'd like everyone to make sure that they're basing your branch off of 1.12 for starters.  Even if that means discarding some commits.  @Illyohs Do you think we should close this PR now?  mention #81 in all your commits to link to the issue and we can continue coordinating from there.

**Comment by 0xilly** [comment]
@josiahseaman just saw #81 and it looks off, Runix should be loaded by forge in this branch

**Pull request closed without merging**
